# Generated by Django 5.2.13 on 2026-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('author', models.CharField(max_length=120, verbose_name='著者')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
                'ordering': ['-published_at', 'id'],
            },
        ),
    ]
